#goal definition
string[] actuator_ids
float64[] position
float64[] velocity
float64[] acceleration
bool relative
---
#result definition
float64[] final_joint_error
bool begun
bool uninterrupted
---
#feedback
float64[] joint_error

